local NAMES: { [string]: string } = {

	["layer.dirt.name"] = "Grassland",
	["layer.stone.name"] = "Stone Layer",
	["layer.limestone.name"] = "Limestone Layer",
	["layer.crimson.name"] = "Crimson Layer",
	["layer.marble.name"] = "Marble Layer",
	["layer.obsidian.name"] = "Obsidian Layer",
	["layer.void.name"] = "Void Layer",
}

return {
	ru = NAMES,
	en = NAMES,
	es = {
		["layer.dirt.name"] = "Pradera",
		["layer.stone.name"] = "Capa de piedra",
		["layer.limestone.name"] = "Capa de piedra caliza",
		["layer.crimson.name"] = "Capa carmesí",
		["layer.marble.name"] = "Capa de mármol",
		["layer.obsidian.name"] = "Capa de obsidiana",
		["layer.void.name"] = "Capa vacía",
	},
	pt = {
		["layer.dirt.name"] = "Pastagem",
		["layer.stone.name"] = "Camada de Pedra",
		["layer.limestone.name"] = "Camada de calcário",
		["layer.crimson.name"] = "Camada Carmesim",
		["layer.marble.name"] = "Camada de Mármore",
		["layer.obsidian.name"] = "Camada Obsidiana",
		["layer.void.name"] = "Camada Vazia",
	},
	de = {
		["layer.dirt.name"] = "Wiese",
		["layer.stone.name"] = "Steinschicht",
		["layer.limestone.name"] = "Kalksteinschicht",
		["layer.crimson.name"] = "Purpurrote Schicht",
		["layer.marble.name"] = "Marmorschicht",
		["layer.obsidian.name"] = "Obsidianschicht",
		["layer.void.name"] = "Leere Schicht",
	},
	fr = {
		["layer.dirt.name"] = "Prairie",
		["layer.stone.name"] = "Couche de pierre",
		["layer.limestone.name"] = "Couche de calcaire",
		["layer.crimson.name"] = "Couche cramoisie",
		["layer.marble.name"] = "Couche de marbre",
		["layer.obsidian.name"] = "Couche d'obsidienne",
		["layer.void.name"] = "Couche vide",
	},
	id = {
		["layer.dirt.name"] = "Padang rumput",
		["layer.stone.name"] = "Lapisan Batu",
		["layer.limestone.name"] = "Lapisan Batu Kapur",
		["layer.crimson.name"] = "Lapisan Merah",
		["layer.marble.name"] = "Lapisan Marmer",
		["layer.obsidian.name"] = "Lapisan Obsidian",
		["layer.void.name"] = "Lapisan Kosong",
	},
	tr = {
		["layer.dirt.name"] = "Otlak",
		["layer.stone.name"] = "Taş Katmanı",
		["layer.limestone.name"] = "Kireçtaşı Katmanı",
		["layer.crimson.name"] = "Kızıl Katman",
		["layer.marble.name"] = "Mermer Katmanı",
		["layer.obsidian.name"] = "Obsidyen Katmanı",
		["layer.void.name"] = "Geçersiz Katman",
	},
}
