--!strict
-- Каталог: загрузочный экран (LoadingScreen).

return {
	ru = {
		["loading.subtitle"] = "Копай глубже · Богатей · Стань легендой шахты",
		["loading.tip.1"] = "Совет: продавайте добытую руду у зелёного пункта ПРОДАТЬ, чтобы получить монеты.",
		["loading.tip.2"] = "Совет: улучшайте кирку — она ломает блоки быстрее и открывает путь глубже.",
		["loading.tip.3"] = "Совет: питомцы дают пассивные бонусы. Открывайте яйца и собирайте редких!",
		["loading.tip.4"] = "Совет: ребёрт сбрасывает прогресс, но даёт постоянный множитель дохода.",
		["loading.tip.5"] = "Совет: чем глубже вы копаете, тем ценнее руда вам встречается.",
		["loading.tip.6"] = "Совет: вводите промокоды в меню, чтобы получить бесплатные награды.",
		["loading.tip.7"] = "Совет: заходите каждый день — ежедневные награды растут вместе со стриком.",
		["loading.tip.8"] = "Совет: бусты и VIP ускоряют добычу и повышают шанс на редкие находки.",
		["loading.skip"] = "Пропустить",
	},
	en = {
		["loading.subtitle"] = "Dig deeper · Get rich · Become a mine legend",
		["loading.tip.1"] = "Tip: sell your mined ore at the green SELL point to earn coins.",
		["loading.tip.2"] = "Tip: upgrade your pickaxe — it breaks blocks faster and opens the way deeper.",
		["loading.tip.3"] = "Tip: pets grant passive bonuses. Open eggs and collect rare ones!",
		["loading.tip.4"] = "Tip: rebirth resets progress but grants a permanent income multiplier.",
		["loading.tip.5"] = "Tip: the deeper you dig, the more valuable the ore you find.",
		["loading.tip.6"] = "Tip: enter promo codes in the menu to get free rewards.",
		["loading.tip.7"] = "Tip: log in every day — daily rewards grow with your streak.",
		["loading.tip.8"] = "Tip: boosts and VIP speed up mining and raise your rare-find chance.",
		["loading.skip"] = "Skip",
	},
	es = {
		["loading.subtitle"] = "Profundiza · Hazte rico · Conviértete en una leyenda minera",
		["loading.tip.1"] = "Consejo: vende el mineral extraído en el punto de VENTA verde para ganar monedas.",
		["loading.tip.2"] = "Consejo: mejora tu pico: rompe bloques más rápido y abre el camino más profundamente.",
		["loading.tip.3"] = "Consejo: las mascotas otorgan bonificaciones pasivas. ¡Abre huevos y recoge los raros!",
		["loading.tip.4"] = "Consejo: el renacimiento restablece el progreso pero otorga un multiplicador de ingresos permanente.",
		["loading.tip.5"] = "Consejo: cuanto más profundo excaves, más valioso será el mineral que encuentres.",
		["loading.tip.6"] = "Consejo: ingrese códigos promocionales en el menú para obtener recompensas gratuitas.",
		["loading.tip.7"] = "Consejo: inicia sesión todos los días: las recompensas diarias crecen con tu racha.",
		["loading.tip.8"] = "Consejo: los aumentos y VIP aceleran la minería y aumentan las posibilidades de encontrar objetos raros.",
		["loading.skip"] = "Saltar",
	},
	pt = {
		["loading.subtitle"] = "Vá mais fundo · Fique rico · Torne-se uma lenda da mina",
		["loading.tip.1"] = "Dica: venda seu minério extraído no ponto verde de VENDA para ganhar moedas.",
		["loading.tip.2"] = "Dica: atualize sua picareta – ela quebra blocos mais rápido e abre caminho mais fundo.",
		["loading.tip.3"] = "Dica: animais de estimação concedem bônus passivos. Abra ovos e colete os raros!",
		["loading.tip.4"] = "Dica: o renascimento redefine o progresso, mas concede um multiplicador de renda permanente.",
		["loading.tip.5"] = "Dica: quanto mais fundo você cavar, mais valioso será o minério encontrado.",
		["loading.tip.6"] = "Dica: insira códigos promocionais no menu para obter recompensas gratuitas.",
		["loading.tip.7"] = "Dica: faça login todos os dias – as recompensas diárias aumentam com a sua sequência.",
		["loading.tip.8"] = "Dica: reforços e VIP aceleram a mineração e aumentam suas chances de encontrar itens raros.",
		["loading.skip"] = "Pular",
	},
	de = {
		["loading.subtitle"] = "Graben Sie tiefer · Werden Sie reich · Werden Sie zur Minenlegende",
		["loading.tip.1"] = "Tipp: Verkaufen Sie Ihr abgebauten Erz am grünen VERKAUFSpunkt, um Münzen zu verdienen.",
		["loading.tip.2"] = "Tipp: Rüsten Sie Ihre Spitzhacke auf – sie bricht Blöcke schneller auf und öffnet den Weg tiefer.",
		["loading.tip.3"] = "Tipp: Haustiere gewähren passive Boni. Öffne Eier und sammle seltene!",
		["loading.tip.4"] = "Tipp: Die Wiedergeburt setzt den Fortschritt zurück, gewährt aber einen dauerhaften Einkommensmultiplikator.",
		["loading.tip.5"] = "Tipp: Je tiefer Sie graben, desto wertvoller ist das Erz, das Sie finden.",
		["loading.tip.6"] = "Tipp: Geben Sie Aktionscodes im Menü ein, um kostenlose Prämien zu erhalten.",
		["loading.tip.7"] = "Tipp: Melden Sie sich jeden Tag an – die täglichen Belohnungen wachsen mit Ihrem Streak.",
		["loading.tip.8"] = "Tipp: Boosts und VIP beschleunigen den Bergbau und erhöhen Ihre Chance auf seltene Funde.",
		["loading.skip"] = "Überspringen",
	},
	fr = {
		["loading.subtitle"] = "Creusez plus profondément · Devenez riche · Devenez une légende de la mine",
		["loading.tip.1"] = "Astuce : vendez votre minerai extrait au point vert SELL pour gagner des pièces.",
		["loading.tip.2"] = "Astuce : améliorez votre pioche : elle brise les blocs plus rapidement et ouvre la voie plus profondément.",
		["loading.tip.3"] = "Astuce : les familiers accordent des bonus passifs. Ouvrez les œufs et collectionnez les rares !",
		["loading.tip.4"] = "Astuce : la renaissance réinitialise la progression mais accorde un multiplicateur de revenu permanent.",
		["loading.tip.5"] = "Astuce : plus vous creusez profondément, plus le minerai que vous trouvez a de la valeur.",
		["loading.tip.6"] = "Astuce : saisissez les codes promotionnels dans le menu pour obtenir des récompenses gratuites.",
		["loading.tip.7"] = "Astuce : connectez-vous tous les jours ; les récompenses quotidiennes augmentent avec votre séquence.",
		["loading.tip.8"] = "Astuce : les boosts et les VIP accélèrent le minage et augmentent vos chances de trouver des objets rares.",
		["loading.skip"] = "Sauter",
	},
	id = {
		["loading.subtitle"] = "Gali lebih dalam · Menjadi kaya · Menjadi legenda tambang",
		["loading.tip.1"] = "Tip: jual bijih tambang Anda di titik JUAL hijau untuk mendapatkan koin.",
		["loading.tip.2"] = "Tip: tingkatkan beliung Anda — ini akan menghancurkan blok lebih cepat dan membuka jalan lebih dalam.",
		["loading.tip.3"] = "Tip: hewan peliharaan memberikan bonus pasif. Buka telur dan kumpulkan yang langka!",
		["loading.tip.4"] = "Tip: kelahiran kembali mengatur ulang kemajuan tetapi memberikan pengganda pendapatan permanen.",
		["loading.tip.5"] = "Tip: semakin dalam Anda menggali, semakin berharga bijih yang Anda temukan.",
		["loading.tip.6"] = "Tip: masukkan kode promo di menu untuk mendapatkan hadiah gratis.",
		["loading.tip.7"] = "Tip: masuk setiap hari — hadiah harian bertambah seiring dengan pukulan Anda.",
		["loading.tip.8"] = "Tip: peningkatan dan VIP mempercepat penambangan dan meningkatkan peluang langka Anda.",
		["loading.skip"] = "Melewati",
	},
	tr = {
		["loading.subtitle"] = "Daha derine inin · Zengin olun · Maden efsanesi olun",
		["loading.tip.1"] = "İpucu: Madeni para kazanmak için çıkardığınız cevheri yeşil SAT noktasında satın.",
		["loading.tip.2"] = "İpucu: kazmanızı yükseltin; blokları daha hızlı kırar ve daha derin bir yol açar.",
		["loading.tip.3"] = "İpucu: evcil hayvanlar pasif bonuslar verir. Yumurtaları açın ve nadir olanları toplayın!",
		["loading.tip.4"] = "İpucu: Yeniden doğuş ilerlemeyi sıfırlar ancak kalıcı bir gelir çarpanı sağlar.",
		["loading.tip.5"] = "İpucu: Ne kadar derine kazarsanız cevher o kadar değerli olur.",
		["loading.tip.6"] = "İpucu: Ücretsiz ödüller kazanmak için menüye promosyon kodlarını girin.",
		["loading.tip.7"] = "İpucu: Her gün giriş yapın; serinizle birlikte günlük ödüller de artar.",
		["loading.tip.8"] = "İpucu: Takviyeler ve VIP, madenciliği hızlandırır ve nadir bulma şansınızı artırır.",
		["loading.skip"] = "Atlamak",
	},
}
