--!strict
-- Каталог: титулы над головой игрока (PlayerTag, server-side).
-- Тег world-space рендерится на сервере для всех зрителей сразу, поэтому
-- локализуется под язык по умолчанию (ru). Пер-зрительскую локализацию
-- overhead-тегов Roblox не поддерживает для серверных BillboardGui.

return {
	ru = {
		["playerTag.tier.god"] = "Бог Шахты",
		["playerTag.tier.master"] = "Мастер",
		["playerTag.tier.legend"] = "Легенда",
		["playerTag.tier.veteran"] = "Ветеран",
		["playerTag.tier.miner"] = "Шахтёр",
		["playerTag.tier.novice"] = "Новичок",
	},
	en = {
		["playerTag.tier.god"] = "Mine God",
		["playerTag.tier.master"] = "Master",
		["playerTag.tier.legend"] = "Legend",
		["playerTag.tier.veteran"] = "Veteran",
		["playerTag.tier.miner"] = "Miner",
		["playerTag.tier.novice"] = "Novice",
	},
	es = {
		["playerTag.tier.god"] = "Dios de la Mina",
		["playerTag.tier.master"] = "Maestro",
		["playerTag.tier.legend"] = "Leyenda",
		["playerTag.tier.veteran"] = "Veterano",
		["playerTag.tier.miner"] = "Minero",
		["playerTag.tier.novice"] = "Novato",
		["playerTag.tier.god"] = "Dios de la Mina",
		["playerTag.tier.master"] = "Maestro",
		["playerTag.tier.legend"] = "Leyenda",
		["playerTag.tier.veteran"] = "Veterano",
		["playerTag.tier.miner"] = "Minero",
		["playerTag.tier.novice"] = "Novato",
	},
	pt = {
		["playerTag.tier.god"] = "Deus da Mina",
		["playerTag.tier.master"] = "Mestre",
		["playerTag.tier.legend"] = "Lenda",
		["playerTag.tier.veteran"] = "Veterano",
		["playerTag.tier.miner"] = "Minerador",
		["playerTag.tier.novice"] = "Novato",
	},
	de = {
		["playerTag.tier.god"] = "Minen-Gott",
		["playerTag.tier.master"] = "Meister",
		["playerTag.tier.legend"] = "Legende",
		["playerTag.tier.veteran"] = "Veteran",
		["playerTag.tier.miner"] = "Bergmann",
		["playerTag.tier.novice"] = "Neuling",
	},
	fr = {
		["playerTag.tier.god"] = "Dieu de la mine",
		["playerTag.tier.master"] = "Maître",
		["playerTag.tier.legend"] = "Légende",
		["playerTag.tier.veteran"] = "Vétéran",
		["playerTag.tier.miner"] = "Mineur",
		["playerTag.tier.novice"] = "Novice",
	},
	id = {
		["playerTag.tier.god"] = "Dewa Tambang",
		["playerTag.tier.master"] = "Master",
		["playerTag.tier.legend"] = "Legenda",
		["playerTag.tier.veteran"] = "Veteran",
		["playerTag.tier.miner"] = "Penambang",
		["playerTag.tier.novice"] = "Pemula",
		["playerTag.tier.god"] = "Dewa Tambang",
		["playerTag.tier.master"] = "Master",
		["playerTag.tier.legend"] = "Legenda",
		["playerTag.tier.veteran"] = "Veteran",
		["playerTag.tier.miner"] = "Penambang",
		["playerTag.tier.novice"] = "Pemula",
	},
	tr = {
		["playerTag.tier.god"] = "Maden Tanrısı",
		["playerTag.tier.master"] = "Usta",
		["playerTag.tier.legend"] = "Efsane",
		["playerTag.tier.veteran"] = "Kıdemli",
		["playerTag.tier.miner"] = "Madenci",
		["playerTag.tier.novice"] = "Acemi",
		["playerTag.tier.god"] = "Maden Tanrısı",
		["playerTag.tier.master"] = "Usta",
		["playerTag.tier.legend"] = "Efsane",
		["playerTag.tier.veteran"] = "Kıdemli",
		["playerTag.tier.miner"] = "Madenci",
		["playerTag.tier.novice"] = "Acemi",
	},
}
