--!strict
-- Каталог: разрозненные строки data-слоя, не попавшие в тематические namespace.
--   leaderboard.* — единица глубины (LeaderboardLogic.formatValue).
--   rebirth.*      — описание награды ребёрта (RebirthLogic.describeReward).
--   egg.*          — подписи количества вылуплений (EggMonetization).
--   server.notify.starterBonus — стартовый тост (TutorialManager).

return {
	ru = {
		["leaderboard.depthMeters"] = "{value} м",
		["rebirth.describeReward"] = "К ценам руд: {now} → {next}",
		["egg.hatchOne"] = "1 вылупление",
		["egg.hatchMany"] = "{count} вылуплений",
		["server.notify.starterBonus"] = "+{coins} монет на старт! Купи свою первую кирку 🪨",
	},
	en = {
		["leaderboard.depthMeters"] = "{value} m",
		["rebirth.describeReward"] = "Ore prices: {now} → {next}",
		["egg.hatchOne"] = "1 hatch",
		["egg.hatchMany"] = "{count} hatches",
		["server.notify.starterBonus"] = "+{coins} coins to start! Buy your first pickaxe 🪨",
	},
	es = {
		["leaderboard.depthMeters"] = "{value} m",
		["rebirth.describeReward"] = "Precios de minerales: {now} → {next}",
		["egg.hatchOne"] = "1 eclosión",
		["egg.hatchMany"] = "{count} eclosiones",
		["server.notify.starterBonus"] = "+{coins} monedas para empezar! Compra tu primer pico 🪨",
		["leaderboard.depthMeters"] = "{value} m",
		["rebirth.describeReward"] = "Precios de minerales: {now} → {next}",
		["egg.hatchOne"] = "1 eclosión",
		["egg.hatchMany"] = "{count} eclosiones",
		["server.notify.starterBonus"] = "+{coins} monedas para empezar! Compra tu primer pico 🪨",
	},
	pt = {
		["leaderboard.depthMeters"] = "{value} m",
		["rebirth.describeReward"] = "Preços dos minérios: {now} → {next}",
		["egg.hatchOne"] = "1 eclosão",
		["egg.hatchMany"] = "{count} eclosões",
		["server.notify.starterBonus"] = "+{coins} moedas para começar! Compre sua primeira picareta 🪨",
		["leaderboard.depthMeters"] = "{value} m",
		["rebirth.describeReward"] = "Preços dos minérios: {now} → {next}",
		["egg.hatchOne"] = "1 chocar",
		["egg.hatchMany"] = "{count} chocar",
		["server.notify.starterBonus"] = "+{coins} moedas para começar! Compre sua primeira picareta 🪨",
	},
	de = {
		["leaderboard.depthMeters"] = "{value} m",
		["rebirth.describeReward"] = "Erzpreise: {now} → {next}",
		["egg.hatchOne"] = "1 Schlüpfen",
		["egg.hatchMany"] = "{count} Schlüpfe",
		["server.notify.starterBonus"] = "+{coins} Münzen zum Start! Kauf deine erste Spitzhacke 🪨",
		["leaderboard.depthMeters"] = "{value} m",
		["rebirth.describeReward"] = "Erzpreise: {now} → {next}",
		["egg.hatchOne"] = "1 Schlüpfen",
		["egg.hatchMany"] = "{count} Schlüpfe",
		["server.notify.starterBonus"] = "+{coins} Münzen zum Start! Kauf deine erste Spitzhacke 🪨",
	},
	fr = {
		["leaderboard.depthMeters"] = "{value} m",
		["rebirth.describeReward"] = "Prix des minerais : {now} → {next}",
		["egg.hatchOne"] = "1 éclosion",
		["egg.hatchMany"] = "{count} éclosions",
		["server.notify.starterBonus"] = "+{coins} pièces pour commencer ! Achetez votre première pioche 🪨",
		["leaderboard.depthMeters"] = "{value} m",
		["rebirth.describeReward"] = "Prix des minerais : {now} → {next}",
		["egg.hatchOne"] = "1 éclosion",
		["egg.hatchMany"] = "{count} éclosions",
		["server.notify.starterBonus"] = "+{coins} pièces pour commencer ! Achetez votre première pioche 🪨",
	},
	id = {
		["leaderboard.depthMeters"] = "{value} m",
		["rebirth.describeReward"] = "Harga bijih: {now} → {next}",
		["egg.hatchOne"] = "1 menetas",
		["egg.hatchMany"] = "{count} menetas",
		["server.notify.starterBonus"] = "+{coins} koin untuk memulai! Beli beliung pertamamu 🪨",
		["leaderboard.depthMeters"] = "{value} m",
		["rebirth.describeReward"] = "Harga bijih: {now} → {next}",
		["egg.hatchOne"] = "1 menetas",
		["egg.hatchMany"] = "{count} menetas",
		["server.notify.starterBonus"] = "+{coins} koin untuk memulai! Beli beliung pertamamu 🪨",
	},
	tr = {
		["leaderboard.depthMeters"] = "{value} m",
		["rebirth.describeReward"] = "Cevher fiyatları: {now} → {next}",
		["egg.hatchOne"] = "1 çıkış",
		["egg.hatchMany"] = "{count} çıkış",
		["server.notify.starterBonus"] = "Başlangıç için +{coins} coin! İlk kazmanı al 🪨",
		["leaderboard.depthMeters"] = "{value} m",
		["rebirth.describeReward"] = "Cevher fiyatları: {now} → {next}",
		["egg.hatchOne"] = "1 kuluçka",
		["egg.hatchMany"] = "{count} kuluçka",
		["server.notify.starterBonus"] = "Başlangıç için +{coins} coin! İlk kazmanı al 🪨",
	},
}
