--!strict
-- Upgrades assets from StarterGui.ScreenGui.Upgrade.

local Assets = {
    titleBar = "rbxassetid://136763918320016",
    close = "rbxassetid://92496407132733",
    icon = "rbxassetid://92900844584670",
    rowBg = "rbxassetid://82161688928908",
    moneyButton = "rbxassetid://104947352542842",
    robuxButton = "rbxassetid://83044089260514",
    robuxIcon = "rbxassetid://88261939855261",
}

return Assets
